[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
"/*" = [
    "Access-Control-Allow-Origin: https://yourserver.com",
    "Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept",
    "Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE"
  ]